services:
  - type: web
    name: code-quest-island
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers=4 --timeout=120 app:app
